---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - local-path-storage.yaml

images:
- name: rancher/local-path-provisioner
  newName: kmjayadeep/local-path-provisioner
  newTag: velero-support
